Repository Dando18/slurm-dashboard, pull requests merged in 2024-01, with the labels that each got.

#20 Use scontrol to get job stdout path
  src/jobs.ts
  src/scheduler.ts
  src/test/suite/scheduler.test.ts
Labels: enhancement

#21 Bump Version to 0.0.8
  CHANGELOG.md
  README.md
  package.json
Labels: release

#28 update codecov settings
  .codecov.yaml
Labels: documentation, enhancement

#29 update codecov settings
  .codecov.yaml
Labels: documentation, enhancement

#30 Increased Testing Coverage
  .vscode/launch.json
  src/extension.ts
  src/jobscripts.ts
  src/test/slurm-wrapper.py
  src/test/suite/fileutilities.test.ts
  src/test/suite/jobs.test.ts
  src/test/suite/jobscripts.test.ts
Labels: testing

#32 Fix Time Parsing Error
  src/scheduler.ts
  src/test/suite/util.test.ts
  src/util.ts
Labels: bug-fix

#33 bump v0.0.9
  CHANGELOG.md
  README.md
  package.json
Labels: release

#49 Add option to use --user instead of --me
  README.md
  package.json
  src/scheduler.ts
Labels: enhancement, bug-fix

#50 bump version to 0.0.10
  CHANGELOG.md
  README.md
  package.json
Labels: release
